# nginx proxy address - http://172.17.0.1:60198

name: snappymail
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: djmaze/snappymail:latest
    container_name: snappymail-app
    domainname: ${BASE_DOMAIN_NAME:-example.com}
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      DEBUG: false
      CONTAINER_NAME: snappymail-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - 172.17.0.1:60198:8888
    volumes:
      - './volumes/data/snappymail:/var/lib/snappymail'
    networks:
      - snappymail
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://snappymail-app:8888'
      - 'cloudflare.hostname=snappymail.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.snappymail-app.entrypoints=http'
      - 'traefik.http.routers.snappymail-app-secure.tls=true'
      - 'traefik.http.routers.snappymail-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.snappymail-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.snappymail-app.middlewares=snappymail-app-https-redirect'
      - 'traefik.http.routers.snappymail-app-secure.entrypoints=https'
      - 'traefik.http.routers.snappymail-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.snappymail-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.snappymail-app-secure.service=snappymail-app'
      - 'traefik.http.services.snappymail-app.loadbalancer.server.port=8888'

  db:
    image: mariadb:latest
    container_name: snappymail-db
    hostname: snappymail-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      MARIADB_USER: ${DB_USER_NAME:-snappymail}
      MARIADB_ROOT_PASSWORD: ${DB_ADMIN_PASS:-changeme_admin_password}
      MARIADB_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      MARIADB_DATABASE: ${DB_CREATE_DATABASE_NAME:-snappymail}
      CONTAINER_NAME: snappymail-db
    volumes:
      - './volumes/data/db/mariadb/snappymail:/var/lib/mysql'
    networks:
      - snappymail

networks:
  snappymail:
    name: snappymail
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
